# Generated by Django 3.0.7 on 2020-06-06 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='actors',
        ),
        migrations.AddField(
            model_name='film',
            name='actors',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='description',
            field=models.TextField(max_length=1024),
        ),
        migrations.DeleteModel(
            name='Actor',
        ),
    ]
